; are you here?

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

pin-workspace = false

label-active = %name%
label-active-background = ${colors.background-apps}
label-active-padding = 1
label-active-foreground = #8D021F

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1



[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%
background = #8D021F

[module/powermenu]
type = custom/menu

expand-right = true
format-spacing = 1
label-open = ""
label-open-foreground = ${colors.urgent}
label-close =  cancel
label-close-foreground = ${colors.success}
label-separator = |
label-separator-foreground = ${colors.foreground}

;Powermenu
menu-0-0 = "Reboot "
menu-0-0-exec = menu-open-1
menu-0-0-foreground = ${colors.urgent}
menu-0-1 = "Power Off"
menu-0-1-exec = menu-open-2
menu-0-1-foreground = ${colors.urgent}
menu-0-2 = "Hibernate"
menu-0-2-exec = menu-open-3
menu-0-2-foreground = ${colors.warning}

;Reboot
menu-1-0 = "Cancel "
menu-1-0-exec = menu-open-0
menu-1-0-foreground = ${colors.success}
menu-1-1 = "Reboot"
menu-1-1-exec = systemctl reboot
menu-1-1-foreground = ${colors.urgent}

;Shutdown
menu-2-0 = "Power off"
menu-2-0-exec = systemctl poweroff
menu-2-0-foreground = ${colors.urgent}
menu-2-1 = "Cancel "
menu-2-1-exec = menu-open-0
menu-2-1-foreground = ${colors.success}

;Hibernate
menu-3-0 = "Hibernate "
menu-3-0-exec = systemctl hibernate
menu-3-0-foreground = ${colors.urgent}
menu-3-1 = "Cancel"
menu-3-1-exec = menu-open-0
menu-3-1-foreground = ${colors.success} 

[module/battery]
type = internal/battery

battery = BAT0
adapter = ADP1
poll-interval = 5

label-charging = %{T1}⚡︎%{T-}%{F#8D021F}%percentage%%
label-discharging = %{F#8D021F}  %{F-}%{F#8D021F}%percentage%%
label-full = %{F#8D021F}  %{F-}%{F#8D021F}%percentage%

label-charging-padding = 2
label-discharging-padding = 2
label-full-padding = 2

format-full-background = ${colors.background-apps}
format-charging-background = ${colors.background-apps}
format-discharging-background = ${colors.background-apps}

[module/filesystem]
type = internal/fs
interval = 10

mount-0 = /

label-mounted =  %{F#b16286}DSK%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = %{F#8D021F}  %{F-} 
format-volume = <label-volume>

label-volume = %{F#9D021F}%percentage%%

format-volume-prefix-foreground = ${colors.foreground}

format-volume-background = ${colors.background-apps}

label-muted = %{F#8D021F} %{F-}
label-muted-padding = 0

label-muted-foreground = ${colors.disabled}

[module/memory]
type = internal/memory
interval = 2
format-prefix =  %{F#8D021F}RAM %{F-}
format-prefix-foreground = ${colors.foreground}
label = %{F#8D021F}%percentage_used:2%%
format-background = ${colors.background-apps}

[module/sep]
type = custom/text
content = "  "

content-foreground = ${colors.background-apps}
content-background = ${colors.background-apps}

[module/sep0]
type = custom/text
content = "◣"

content-foreground = ${colors.background-alt}
content-background = ${colors.background}

[module/sep1]
type = custom/text
content = ◢
content-font = 20

# content-foreground = ${colors.background-alt}
content-background = ${F#8D021F}%

[module/sep2]
type = custom/text
content = "  "

content-foreground = ${colors.background-alt}
content-background = ${colors.background}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix =  %{F#8D021F}   %{F-}
format-prefix-foreground = ${colors.foreground}
label = %{F#8D021F}%percentage:2%%    
format-background = ${colors.background-apps}

[module/date]
type = internal/date
interval = 1

date = %H:%M:%S
date-alt = %Y-%m-%d

format-background = ${colors.background-apps}

label = %{F#8D021F}%date%
; label-background = ${colors.background-alt}
;label-foreground = ${F#b16286}


[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
format-packetloss = <animation-packetloss><label-connected>
label-connected = %{F#8D021F}󰤨 %{F-}
label-disconnected = %{F#8D021F}no wifi :(%{F-}
label-connected-padding = 1
label-disconnected-padding = 1
label-connected-foreground = #ffffff
format-connected-background = ${colors.background-apps}
format-disconnected-background = ${colors.background-apps}

[module/wlan]
inherit = network-base
interface-type = wireless


